apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: solr-config
  name: solr-config
spec:
  type: NodePort
  ports:
  - name: headless
    port: 8983
  selector:
    io.kompose.service: solr-config
status:
  loadBalancer: {}

