apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: solr-config
  name: solr-config
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: solr-config
    spec:
      nodeSelector:
        name: minion02
      containers:
      - image: solr:latest
        name: solr-config
        ports:
        - containerPort: 8983
        resources: {}
        volumeMounts:
        - mountPath: /opt/solr/server/solr/egar-gar-search/
          name: egar-gar-search
        - mountPath: /opt/solr/server/solr/egar-people-search/
          name: egar-people-search
        - mountPath: /opt/solr/server/solr/egar-bill/
          name: egar-bill
      restartPolicy: Always
      volumes:
      - name: egar-gar-search
        hostPath:
          path: /home/centos/solr/egar-gar-search
      - name: egar-people-search
        hostPath:
          path: /home/centos/solr/egar-people-search
      - name: egar-bill
        hostPath:
          path: /home/centos/solr/egar-bill
status: {}

